//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaActas.CompromisoService {
    using System.Runtime.Serialization;
    using System;
    using SistemaActas.ActaServices;

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VersionCompromiso", Namespace="http://schemas.datacontract.org/2004/07/WS_Actas.Model")]
    [System.SerializableAttribute()]
    public partial class VersionCompromiso : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string anotacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string descripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string fecha_compromisoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int id_compromisoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int id_estadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int id_usuario_asignadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int id_version_compromisoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string anotacion {
            get {
                return this.anotacionField;
            }
            set {
                if ((object.ReferenceEquals(this.anotacionField, value) != true)) {
                    this.anotacionField = value;
                    this.RaisePropertyChanged("anotacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.descripcionField, value) != true)) {
                    this.descripcionField = value;
                    this.RaisePropertyChanged("descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string fecha_compromiso {
            get {
                return this.fecha_compromisoField;
            }
            set {
                if ((object.ReferenceEquals(this.fecha_compromisoField, value) != true)) {
                    this.fecha_compromisoField = value;
                    this.RaisePropertyChanged("fecha_compromiso");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id_compromiso {
            get {
                return this.id_compromisoField;
            }
            set {
                if ((this.id_compromisoField.Equals(value) != true)) {
                    this.id_compromisoField = value;
                    this.RaisePropertyChanged("id_compromiso");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id_estado {
            get {
                return this.id_estadoField;
            }
            set {
                if ((this.id_estadoField.Equals(value) != true)) {
                    this.id_estadoField = value;
                    this.RaisePropertyChanged("id_estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id_usuario_asignado {
            get {
                return this.id_usuario_asignadoField;
            }
            set {
                if ((this.id_usuario_asignadoField.Equals(value) != true)) {
                    this.id_usuario_asignadoField = value;
                    this.RaisePropertyChanged("id_usuario_asignado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id_version_compromiso {
            get {
                return this.id_version_compromisoField;
            }
            set {
                if ((this.id_version_compromisoField.Equals(value) != true)) {
                    this.id_version_compromisoField = value;
                    this.RaisePropertyChanged("id_version_compromiso");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }

        public static implicit operator VersionCompromiso(ActaServices.VersionCompromiso v)
        {
            throw new NotImplementedException();
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Estado", Namespace="http://schemas.datacontract.org/2004/07/WS_Actas.Model")]
    [System.SerializableAttribute()]
    public partial class Estado : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string descripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int id_estadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nombreField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.descripcionField, value) != true)) {
                    this.descripcionField = value;
                    this.RaisePropertyChanged("descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id_estado {
            get {
                return this.id_estadoField;
            }
            set {
                if ((this.id_estadoField.Equals(value) != true)) {
                    this.id_estadoField = value;
                    this.RaisePropertyChanged("id_estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                if ((object.ReferenceEquals(this.nombreField, value) != true)) {
                    this.nombreField = value;
                    this.RaisePropertyChanged("nombre");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CompromisoService.IServiceVersionesCompromiso")]
    public interface IServiceVersionesCompromiso {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceVersionesCompromiso/CrearVersionCompromiso", ReplyAction="http://tempuri.org/IServiceVersionesCompromiso/CrearVersionCompromisoResponse")]
        void CrearVersionCompromiso(string descripcion, string fecha_compromiso, int id_compromiso, int id_estado, string anotacion, int id_usuario_asignado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceVersionesCompromiso/CrearVersionCompromiso", ReplyAction="http://tempuri.org/IServiceVersionesCompromiso/CrearVersionCompromisoResponse")]
        System.Threading.Tasks.Task CrearVersionCompromisoAsync(string descripcion, string fecha_compromiso, int id_compromiso, int id_estado, string anotacion, int id_usuario_asignado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceVersionesCompromiso/ObtenerVersionesCompromisos", ReplyAction="http://tempuri.org/IServiceVersionesCompromiso/ObtenerVersionesCompromisosRespons" +
            "e")]
        SistemaActas.CompromisoService.VersionCompromiso[] ObtenerVersionesCompromisos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceVersionesCompromiso/ObtenerVersionesCompromisos", ReplyAction="http://tempuri.org/IServiceVersionesCompromiso/ObtenerVersionesCompromisosRespons" +
            "e")]
        System.Threading.Tasks.Task<SistemaActas.CompromisoService.VersionCompromiso[]> ObtenerVersionesCompromisosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceVersionesCompromiso/ObtenerVersionCompromiso", ReplyAction="http://tempuri.org/IServiceVersionesCompromiso/ObtenerVersionCompromisoResponse")]
        SistemaActas.CompromisoService.VersionCompromiso ObtenerVersionCompromiso(string idVersionCompromiso);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceVersionesCompromiso/ObtenerVersionCompromiso", ReplyAction="http://tempuri.org/IServiceVersionesCompromiso/ObtenerVersionCompromisoResponse")]
        System.Threading.Tasks.Task<SistemaActas.CompromisoService.VersionCompromiso> ObtenerVersionCompromisoAsync(string idVersionCompromiso);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceVersionesCompromiso/ActualizarVersionCompromiso", ReplyAction="http://tempuri.org/IServiceVersionesCompromiso/ActualizarVersionCompromisoRespons" +
            "e")]
        void ActualizarVersionCompromiso(int id_version_compromiso, string descripcion, string fecha_compromiso, int id_compromiso, int id_estado, string anotacion, int id_usuario_asignado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceVersionesCompromiso/ActualizarVersionCompromiso", ReplyAction="http://tempuri.org/IServiceVersionesCompromiso/ActualizarVersionCompromisoRespons" +
            "e")]
        System.Threading.Tasks.Task ActualizarVersionCompromisoAsync(int id_version_compromiso, string descripcion, string fecha_compromiso, int id_compromiso, int id_estado, string anotacion, int id_usuario_asignado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceVersionesCompromiso/ObtenerEstados", ReplyAction="http://tempuri.org/IServiceVersionesCompromiso/ObtenerEstadosResponse")]
        SistemaActas.CompromisoService.Estado[] ObtenerEstados();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceVersionesCompromiso/ObtenerEstados", ReplyAction="http://tempuri.org/IServiceVersionesCompromiso/ObtenerEstadosResponse")]
        System.Threading.Tasks.Task<SistemaActas.CompromisoService.Estado[]> ObtenerEstadosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceVersionesCompromiso/ObtenerVersionesDeCompromiso", ReplyAction="http://tempuri.org/IServiceVersionesCompromiso/ObtenerVersionesDeCompromisoRespon" +
            "se")]
        SistemaActas.CompromisoService.VersionCompromiso[] ObtenerVersionesDeCompromiso(string idCompromiso);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceVersionesCompromiso/ObtenerVersionesDeCompromiso", ReplyAction="http://tempuri.org/IServiceVersionesCompromiso/ObtenerVersionesDeCompromisoRespon" +
            "se")]
        System.Threading.Tasks.Task<SistemaActas.CompromisoService.VersionCompromiso[]> ObtenerVersionesDeCompromisoAsync(string idCompromiso);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceVersionesCompromiso/ObtenerUltimaVersionDeCompromiso", ReplyAction="http://tempuri.org/IServiceVersionesCompromiso/ObtenerUltimaVersionDeCompromisoRe" +
            "sponse")]
        SistemaActas.CompromisoService.VersionCompromiso ObtenerUltimaVersionDeCompromiso(string idCompromiso);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceVersionesCompromiso/ObtenerUltimaVersionDeCompromiso", ReplyAction="http://tempuri.org/IServiceVersionesCompromiso/ObtenerUltimaVersionDeCompromisoRe" +
            "sponse")]
        System.Threading.Tasks.Task<SistemaActas.CompromisoService.VersionCompromiso> ObtenerUltimaVersionDeCompromisoAsync(string idCompromiso);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceVersionesCompromisoChannel : SistemaActas.CompromisoService.IServiceVersionesCompromiso, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceVersionesCompromisoClient : System.ServiceModel.ClientBase<SistemaActas.CompromisoService.IServiceVersionesCompromiso>, SistemaActas.CompromisoService.IServiceVersionesCompromiso {
        
        public ServiceVersionesCompromisoClient() {
        }
        
        public ServiceVersionesCompromisoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceVersionesCompromisoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceVersionesCompromisoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceVersionesCompromisoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void CrearVersionCompromiso(string descripcion, string fecha_compromiso, int id_compromiso, int id_estado, string anotacion, int id_usuario_asignado) {
            base.Channel.CrearVersionCompromiso(descripcion, fecha_compromiso, id_compromiso, id_estado, anotacion, id_usuario_asignado);
        }
        
        public System.Threading.Tasks.Task CrearVersionCompromisoAsync(string descripcion, string fecha_compromiso, int id_compromiso, int id_estado, string anotacion, int id_usuario_asignado) {
            return base.Channel.CrearVersionCompromisoAsync(descripcion, fecha_compromiso, id_compromiso, id_estado, anotacion, id_usuario_asignado);
        }
        
        public SistemaActas.CompromisoService.VersionCompromiso[] ObtenerVersionesCompromisos() {
            return base.Channel.ObtenerVersionesCompromisos();
        }
        
        public System.Threading.Tasks.Task<SistemaActas.CompromisoService.VersionCompromiso[]> ObtenerVersionesCompromisosAsync() {
            return base.Channel.ObtenerVersionesCompromisosAsync();
        }
        
        public SistemaActas.CompromisoService.VersionCompromiso ObtenerVersionCompromiso(string idVersionCompromiso) {
            return base.Channel.ObtenerVersionCompromiso(idVersionCompromiso);
        }
        
        public System.Threading.Tasks.Task<SistemaActas.CompromisoService.VersionCompromiso> ObtenerVersionCompromisoAsync(string idVersionCompromiso) {
            return base.Channel.ObtenerVersionCompromisoAsync(idVersionCompromiso);
        }
        
        public void ActualizarVersionCompromiso(int id_version_compromiso, string descripcion, string fecha_compromiso, int id_compromiso, int id_estado, string anotacion, int id_usuario_asignado) {
            base.Channel.ActualizarVersionCompromiso(id_version_compromiso, descripcion, fecha_compromiso, id_compromiso, id_estado, anotacion, id_usuario_asignado);
        }
        
        public System.Threading.Tasks.Task ActualizarVersionCompromisoAsync(int id_version_compromiso, string descripcion, string fecha_compromiso, int id_compromiso, int id_estado, string anotacion, int id_usuario_asignado) {
            return base.Channel.ActualizarVersionCompromisoAsync(id_version_compromiso, descripcion, fecha_compromiso, id_compromiso, id_estado, anotacion, id_usuario_asignado);
        }
        
        public SistemaActas.CompromisoService.Estado[] ObtenerEstados() {
            return base.Channel.ObtenerEstados();
        }
        
        public System.Threading.Tasks.Task<SistemaActas.CompromisoService.Estado[]> ObtenerEstadosAsync() {
            return base.Channel.ObtenerEstadosAsync();
        }
        
        public SistemaActas.CompromisoService.VersionCompromiso[] ObtenerVersionesDeCompromiso(string idCompromiso) {
            return base.Channel.ObtenerVersionesDeCompromiso(idCompromiso);
        }
        
        public System.Threading.Tasks.Task<SistemaActas.CompromisoService.VersionCompromiso[]> ObtenerVersionesDeCompromisoAsync(string idCompromiso) {
            return base.Channel.ObtenerVersionesDeCompromisoAsync(idCompromiso);
        }
        
        public SistemaActas.CompromisoService.VersionCompromiso ObtenerUltimaVersionDeCompromiso(string idCompromiso) {
            return base.Channel.ObtenerUltimaVersionDeCompromiso(idCompromiso);
        }
        
        public System.Threading.Tasks.Task<SistemaActas.CompromisoService.VersionCompromiso> ObtenerUltimaVersionDeCompromisoAsync(string idCompromiso) {
            return base.Channel.ObtenerUltimaVersionDeCompromisoAsync(idCompromiso);
        }
    }
}
