//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaActas.WS_Actas {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Acta", Namespace="http://schemas.datacontract.org/2004/07/WS_Actas.Model")]
    [System.SerializableAttribute()]
    public partial class Acta : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string anotacionesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string descripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string fechaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int id_actaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int id_proyectoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nombreField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string anotaciones {
            get {
                return this.anotacionesField;
            }
            set {
                if ((object.ReferenceEquals(this.anotacionesField, value) != true)) {
                    this.anotacionesField = value;
                    this.RaisePropertyChanged("anotaciones");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.descripcionField, value) != true)) {
                    this.descripcionField = value;
                    this.RaisePropertyChanged("descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string fecha {
            get {
                return this.fechaField;
            }
            set {
                if ((object.ReferenceEquals(this.fechaField, value) != true)) {
                    this.fechaField = value;
                    this.RaisePropertyChanged("fecha");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id_acta {
            get {
                return this.id_actaField;
            }
            set {
                if ((this.id_actaField.Equals(value) != true)) {
                    this.id_actaField = value;
                    this.RaisePropertyChanged("id_acta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id_proyecto {
            get {
                return this.id_proyectoField;
            }
            set {
                if ((this.id_proyectoField.Equals(value) != true)) {
                    this.id_proyectoField = value;
                    this.RaisePropertyChanged("id_proyecto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                if ((object.ReferenceEquals(this.nombreField, value) != true)) {
                    this.nombreField = value;
                    this.RaisePropertyChanged("nombre");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VersionCompromiso", Namespace="http://schemas.datacontract.org/2004/07/WS_Actas.Model")]
    [System.SerializableAttribute()]
    public partial class VersionCompromiso : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string anotacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string descripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string fecha_compromisoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int id_compromisoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int id_estadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int id_usuario_asignadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int id_version_compromisoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string anotacion {
            get {
                return this.anotacionField;
            }
            set {
                if ((object.ReferenceEquals(this.anotacionField, value) != true)) {
                    this.anotacionField = value;
                    this.RaisePropertyChanged("anotacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.descripcionField, value) != true)) {
                    this.descripcionField = value;
                    this.RaisePropertyChanged("descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string fecha_compromiso {
            get {
                return this.fecha_compromisoField;
            }
            set {
                if ((object.ReferenceEquals(this.fecha_compromisoField, value) != true)) {
                    this.fecha_compromisoField = value;
                    this.RaisePropertyChanged("fecha_compromiso");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id_compromiso {
            get {
                return this.id_compromisoField;
            }
            set {
                if ((this.id_compromisoField.Equals(value) != true)) {
                    this.id_compromisoField = value;
                    this.RaisePropertyChanged("id_compromiso");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id_estado {
            get {
                return this.id_estadoField;
            }
            set {
                if ((this.id_estadoField.Equals(value) != true)) {
                    this.id_estadoField = value;
                    this.RaisePropertyChanged("id_estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id_usuario_asignado {
            get {
                return this.id_usuario_asignadoField;
            }
            set {
                if ((this.id_usuario_asignadoField.Equals(value) != true)) {
                    this.id_usuario_asignadoField = value;
                    this.RaisePropertyChanged("id_usuario_asignado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id_version_compromiso {
            get {
                return this.id_version_compromisoField;
            }
            set {
                if ((this.id_version_compromisoField.Equals(value) != true)) {
                    this.id_version_compromisoField = value;
                    this.RaisePropertyChanged("id_version_compromiso");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WS_Actas.IServiceActas")]
    public interface IServiceActas {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceActas/CrearActa", ReplyAction="http://tempuri.org/IServiceActas/CrearActaResponse")]
        void CrearActa(string nombre, string descripcion, string anotaciones, string fecha, int id_proyecto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceActas/CrearActa", ReplyAction="http://tempuri.org/IServiceActas/CrearActaResponse")]
        System.Threading.Tasks.Task CrearActaAsync(string nombre, string descripcion, string anotaciones, string fecha, int id_proyecto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceActas/ObtenerActas", ReplyAction="http://tempuri.org/IServiceActas/ObtenerActasResponse")]
        SistemaActas.WS_Actas.Acta[] ObtenerActas();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceActas/ObtenerActas", ReplyAction="http://tempuri.org/IServiceActas/ObtenerActasResponse")]
        System.Threading.Tasks.Task<SistemaActas.WS_Actas.Acta[]> ObtenerActasAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceActas/ObtenerActa", ReplyAction="http://tempuri.org/IServiceActas/ObtenerActaResponse")]
        SistemaActas.WS_Actas.Acta ObtenerActa(string idActa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceActas/ObtenerActa", ReplyAction="http://tempuri.org/IServiceActas/ObtenerActaResponse")]
        System.Threading.Tasks.Task<SistemaActas.WS_Actas.Acta> ObtenerActaAsync(string idActa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceActas/ActualizarActa", ReplyAction="http://tempuri.org/IServiceActas/ActualizarActaResponse")]
        void ActualizarActa(int id_acta, string nombre, string descripcion, string anotaciones, int id_proyecto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceActas/ActualizarActa", ReplyAction="http://tempuri.org/IServiceActas/ActualizarActaResponse")]
        System.Threading.Tasks.Task ActualizarActaAsync(int id_acta, string nombre, string descripcion, string anotaciones, int id_proyecto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceActas/ObtenerCompromisosPorActa", ReplyAction="http://tempuri.org/IServiceActas/ObtenerCompromisosPorActaResponse")]
        SistemaActas.WS_Actas.VersionCompromiso[] ObtenerCompromisosPorActa(string idActa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceActas/ObtenerCompromisosPorActa", ReplyAction="http://tempuri.org/IServiceActas/ObtenerCompromisosPorActaResponse")]
        System.Threading.Tasks.Task<SistemaActas.WS_Actas.VersionCompromiso[]> ObtenerCompromisosPorActaAsync(string idActa);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceActasChannel : SistemaActas.WS_Actas.IServiceActas, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceActasClient : System.ServiceModel.ClientBase<SistemaActas.WS_Actas.IServiceActas>, SistemaActas.WS_Actas.IServiceActas {
        
        public ServiceActasClient() {
        }
        
        public ServiceActasClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceActasClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceActasClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceActasClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void CrearActa(string nombre, string descripcion, string anotaciones, string fecha, int id_proyecto) {
            base.Channel.CrearActa(nombre, descripcion, anotaciones, fecha, id_proyecto);
        }
        
        public System.Threading.Tasks.Task CrearActaAsync(string nombre, string descripcion, string anotaciones, string fecha, int id_proyecto) {
            return base.Channel.CrearActaAsync(nombre, descripcion, anotaciones, fecha, id_proyecto);
        }
        
        public SistemaActas.WS_Actas.Acta[] ObtenerActas() {
            return base.Channel.ObtenerActas();
        }
        
        public System.Threading.Tasks.Task<SistemaActas.WS_Actas.Acta[]> ObtenerActasAsync() {
            return base.Channel.ObtenerActasAsync();
        }
        
        public SistemaActas.WS_Actas.Acta ObtenerActa(string idActa) {
            return base.Channel.ObtenerActa(idActa);
        }
        
        public System.Threading.Tasks.Task<SistemaActas.WS_Actas.Acta> ObtenerActaAsync(string idActa) {
            return base.Channel.ObtenerActaAsync(idActa);
        }
        
        public void ActualizarActa(int id_acta, string nombre, string descripcion, string anotaciones, int id_proyecto) {
            base.Channel.ActualizarActa(id_acta, nombre, descripcion, anotaciones, id_proyecto);
        }
        
        public System.Threading.Tasks.Task ActualizarActaAsync(int id_acta, string nombre, string descripcion, string anotaciones, int id_proyecto) {
            return base.Channel.ActualizarActaAsync(id_acta, nombre, descripcion, anotaciones, id_proyecto);
        }
        
        public SistemaActas.WS_Actas.VersionCompromiso[] ObtenerCompromisosPorActa(string idActa) {
            return base.Channel.ObtenerCompromisosPorActa(idActa);
        }
        
        public System.Threading.Tasks.Task<SistemaActas.WS_Actas.VersionCompromiso[]> ObtenerCompromisosPorActaAsync(string idActa) {
            return base.Channel.ObtenerCompromisosPorActaAsync(idActa);
        }
    }
}
